/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/export_as_namespace/export_as_namespace.d.ts:
/** @const */
const test_files$export_as_namespace$export_as_namespace = {};
/** @const */
test_files$export_as_namespace$export_as_namespace.foo = {};
/**
 * @constructor
 * @struct
 */
test_files$export_as_namespace$export_as_namespace.foo.Bar = function() {};

/**
 * @return {void}
 */
test_files$export_as_namespace$export_as_namespace.foo.Bar.prototype.baz = function() {};
// 'export as namespace' ignored: use shims to reference modules.

// Publish non-shimmed external module externs as a Closure namespace.
goog.provide('test_files.export_as_namespace.export_as_namespace');
/** @const */
test_files.export_as_namespace.export_as_namespace = test_files$export_as_namespace$export_as_namespace;
