/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/decorator_nested_scope/decorator_nested_scope.ts:
/** @const */
const test_files$decorator_nested_scope$decorator_nested_scope = {};
 /** @type {?} */
test_files$decorator_nested_scope$decorator_nested_scope.Component;
