/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/declare_export_dts/declare_export_dts.d.ts:
/** @const */
const test_files$declare_export_dts$declare_export_dts = {};
/**
 * @record
 * @struct
 */
test_files$declare_export_dts$declare_export_dts.InterfaceExportedInDts = function() {};
 /** @type {!test_files$declare_export_dts$declare_export_dts.InterfaceUsedByExportedInDts} */
test_files$declare_export_dts$declare_export_dts.InterfaceExportedInDts.prototype.nestedInterface;
/**
 * @record
 * @struct
 */
test_files$declare_export_dts$declare_export_dts.InterfaceUsedByExportedInDts = function() {};
 /** @type {string} */
test_files$declare_export_dts$declare_export_dts.InterfaceUsedByExportedInDts.prototype.property;

// Publish non-shimmed external module externs as a Closure namespace.
goog.provide('test_files.declare_export_dts.declare_export_dts');
/** @const */
test_files.declare_export_dts.declare_export_dts = test_files$declare_export_dts$declare_export_dts;
