/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/export_as_namespace_importeq/export_as_namespace_importeq.d.ts:
/** @const */
const test_files$export_as_namespace_importeq$export_as_namespace_importeq = {};
/** @const */
test_files$export_as_namespace_importeq$export_as_namespace_importeq.anamespace = {};
/**
 * @constructor
 * @struct
 */
test_files$export_as_namespace_importeq$export_as_namespace_importeq.anamespace.NamespacedClass = function() {};

/**
 * @return {string}
 */
test_files$export_as_namespace_importeq$export_as_namespace_importeq.anamespace.NamespacedClass.prototype.method = function() {};
// 'export =' ignored: use shims to reference modules.
// 'export as namespace' ignored: use shims to reference modules.

// Publish non-shimmed external module externs as a Closure namespace.
goog.provide('test_files.export_as_namespace_importeq.export_as_namespace_importeq');
/** @const */
test_files.export_as_namespace_importeq.export_as_namespace_importeq = test_files$export_as_namespace_importeq$export_as_namespace_importeq;
