/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/augment/angular-augment.d.ts:
/** @const */
const test_files$augment$angular_augment = {};
// Derived from: declare module "./angular"
/**
 * @record
 * @struct
 */
test_files$augment$angular$index.sub.AugmentSubType = function() {};
 /** @type {string} */
test_files$augment$angular$index.sub.AugmentSubType.prototype.prop;
/** @const */
test_files$augment$angular$index.local = {};

/** @typedef {string} */
test_files$augment$angular$index.local.LocalType;

/** @typedef {!Scope} */
test_files$augment$angular$index.local.UsingSymbolFromAugmentedModule;

// Publish non-shimmed external module externs as a Closure namespace.
goog.provide('test_files.augment.angular_augment');
/** @const */
test_files.augment.angular_augment = test_files$augment$angular_augment;
// externs from test_files/augment/angular/index.d.ts:
/** @const */
const test_files$augment$angular$index = {};
// 'export =' ignored: use shims to reference modules.
// 'export as namespace' ignored: use shims to reference modules.
 /** @type {!IAngularStatic} */
test_files$augment$angular$index.angular;
/**
 * @record
 * @struct
 */
test_files$augment$angular$index.angular.Scope = function() {};
 /** @type {string} */
test_files$augment$angular$index.angular.Scope.prototype.name;
/** @const */
test_files$augment$angular$index.angular.sub = {};

/** @typedef {string} */
test_files$augment$angular$index.angular.sub.SubType;
/**
 * @record
 * @struct
 */
test_files$augment$angular$index.angular.IAngularStatic = function() {};
 /** @type {string} */
test_files$augment$angular$index.angular.IAngularStatic.prototype.version;

/**
 * @param {string} a
 * @return {string}
 */
test_files$augment$angular$index.angular.IAngularStatic.prototype.copy = function(a) {};

// Publish non-shimmed external module externs as a Closure namespace.
goog.provide('test_files.augment.angular.index');
/** @const */
test_files.augment.angular.index = test_files$augment$angular$index;
