/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/export_equals.shim/namespace.d.ts:
/** @const */
const test_files$export_equals$shim$namespace = {};
// 'export =' ignored: use shims to reference modules.
// 'export as namespace' ignored: use shims to reference modules.
/** @const */
test_files$export_equals$shim$namespace.SomeNamespace = {};
/**
 * @constructor
 * @struct
 */
test_files$export_equals$shim$namespace.SomeNamespace.Clazz = function() {};
