/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/underscore/underscore.ts:
/** @const */
const test_files$underscore$underscore = {};
/** @const */
test_files$underscore$underscore.__NS = {};
 /** @type {number} */
test_files$underscore$underscore.__NS.__ns1;
